"""Create all tables

Revision ID: 1479318fbd0a
Revises: 
Create Date: 2025-10-13 10:42:34.295711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1479318fbd0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=255), nullable=False),
    sa.Column('email_contact', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_actif'), 'clients', ['actif'], unique=False)
    op.create_index(op.f('ix_clients_email_contact'), 'clients', ['email_contact'], unique=True)
    op.create_index(op.f('ix_clients_nom_entreprise'), 'clients', ['nom_entreprise'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('nom_site', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('quartier', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('coordonnees_auto', sa.Boolean(), nullable=False),
    sa.Column('precision_gps', sa.Enum('exacte', 'approximative', 'inconnue', name='gps_precision'), nullable=False),
    sa.Column('contact_site', sa.String(length=255), nullable=True),
    sa.Column('telephone_site', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_actif'), 'sites', ['actif'], unique=False)
    op.create_index(op.f('ix_sites_client_id'), 'sites', ['client_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('tuya_device_id', sa.String(length=255), nullable=False),
    sa.Column('nom_appareil', sa.String(length=255), nullable=False),
    sa.Column('type_appareil', sa.String(length=100), nullable=False),
    sa.Column('emplacement', sa.String(length=255), nullable=True),
    sa.Column('type_systeme', sa.Enum('monophase', 'triphase', name='electrical_system_type'), nullable=False),
    sa.Column('statut_assignation', sa.Enum('non_assigne', 'assigne', name='device_assignment_status'), nullable=False),
    sa.Column('tuya_nom_original', sa.String(length=255), nullable=True),
    sa.Column('tuya_modele', sa.String(length=100), nullable=True),
    sa.Column('tuya_version_firmware', sa.String(length=50), nullable=True),
    sa.Column('seuil_tension_min', sa.Float(), nullable=True),
    sa.Column('seuil_tension_max', sa.Float(), nullable=True),
    sa.Column('seuil_courant_max', sa.Float(), nullable=True),
    sa.Column('seuil_puissance_max', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l1_min', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l1_max', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l2_min', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l2_max', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l3_min', sa.Float(), nullable=True),
    sa.Column('seuil_tension_l3_max', sa.Float(), nullable=True),
    sa.Column('seuil_courant_l1_max', sa.Float(), nullable=True),
    sa.Column('seuil_courant_l2_max', sa.Float(), nullable=True),
    sa.Column('seuil_courant_l3_max', sa.Float(), nullable=True),
    sa.Column('seuil_desequilibre_tension', sa.Float(), nullable=True),
    sa.Column('seuil_desequilibre_courant', sa.Float(), nullable=True),
    sa.Column('seuil_facteur_puissance_min', sa.Float(), nullable=True),
    sa.Column('seuil_temperature_max', sa.Float(), nullable=True),
    sa.Column('protection_automatique_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('protection_courant_config', sa.JSON(), nullable=True),
    sa.Column('protection_puissance_config', sa.JSON(), nullable=True),
    sa.Column('protection_temperature_config', sa.JSON(), nullable=True),
    sa.Column('protection_tension_config', sa.JSON(), nullable=True),
    sa.Column('protection_desequilibre_config', sa.JSON(), nullable=True),
    sa.Column('protection_triggers_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('derniere_protection_declenchee', sa.DateTime(), nullable=True),
    sa.Column('derniere_protection_type', sa.String(length=50), nullable=True),
    sa.Column('protection_status', sa.Enum('normal', 'protected', 'error', name='protection_status_type'), server_default='normal', nullable=False),
    sa.Column('programmation_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('horaires_config', sa.JSON(), nullable=True),
    sa.Column('prochaine_action_programmee', sa.DateTime(), nullable=True),
    sa.Column('prochaine_action_type', sa.Enum('turn_on', 'turn_off', 'custom', name='scheduled_action_type'), nullable=True),
    sa.Column('derniere_action_programmee', sa.DateTime(), nullable=True),
    sa.Column('derniere_action_programmee_type', sa.String(length=20), nullable=True),
    sa.Column('derniere_action_programmee_status', sa.Boolean(), nullable=True),
    sa.Column('mode_manuel_actif', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mode_manuel_jusqu', sa.DateTime(), nullable=True),
    sa.Column('date_installation', sa.DateTime(), nullable=False),
    sa.Column('date_assignation', sa.DateTime(), nullable=True),
    sa.Column('derniere_donnee', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('en_ligne', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('etat_actuel_tuya', sa.Boolean(), nullable=True),
    sa.Column('derniere_maj_etat_tuya', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_actif'), 'devices', ['actif'], unique=False)
    op.create_index(op.f('ix_devices_client_id'), 'devices', ['client_id'], unique=False)
    op.create_index(op.f('ix_devices_en_ligne'), 'devices', ['en_ligne'], unique=False)
    op.create_index(op.f('ix_devices_programmation_active'), 'devices', ['programmation_active'], unique=False)
    op.create_index(op.f('ix_devices_protection_automatique_active'), 'devices', ['protection_automatique_active'], unique=False)
    op.create_index(op.f('ix_devices_protection_status'), 'devices', ['protection_status'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_statut_assignation'), 'devices', ['statut_assignation'], unique=False)
    op.create_index(op.f('ix_devices_tuya_device_id'), 'devices', ['tuya_device_id'], unique=True)
    op.create_index(op.f('ix_devices_type_systeme'), 'devices', ['type_systeme'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'user', name='user_roles'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_actif'), 'users', ['actif'], unique=False)
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nom'), 'users', ['nom'], unique=False)
    op.create_index(op.f('ix_users_prenom'), 'users', ['prenom'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('appareil_id', sa.String(length=36), nullable=False),
    sa.Column('type_systeme', sa.Enum('monophase', 'triphase', name='system_type_alert'), nullable=False),
    sa.Column('type_alerte', sa.Enum('seuil_depasse', 'hors_ligne', 'erreur_communication', 'consommation_anormale', 'temperature_haute', 'autre', 'desequilibre_tension', 'desequilibre_courant', 'facteur_puissance_faible', 'perte_phase', 'inversion_phase', 'harmoniques_elevees', 'surtension_composee', 'defaut_neutre', name='alert_types_extended'), nullable=False),
    sa.Column('gravite', sa.Enum('info', 'warning', 'critique', name='alert_severity'), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('phase_concernee', sa.Enum('L1', 'L2', 'L3', 'neutre', 'toutes', name='phase_type'), nullable=True),
    sa.Column('valeur_mesuree', sa.Float(), nullable=True),
    sa.Column('valeur_seuil', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=10), nullable=True),
    sa.Column('valeurs_phases', sa.JSON(), nullable=True),
    sa.Column('seuils_phases', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('nouvelle', 'vue', 'resolue', name='alert_status'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_resolution', sa.DateTime(), nullable=True),
    sa.Column('resolu_par', sa.String(length=36), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appareil_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_appareil_id'), 'alerts', ['appareil_id'], unique=False)
    op.create_index(op.f('ix_alerts_client_id'), 'alerts', ['client_id'], unique=False)
    op.create_index(op.f('ix_alerts_date_creation'), 'alerts', ['date_creation'], unique=False)
    op.create_index(op.f('ix_alerts_gravite'), 'alerts', ['gravite'], unique=False)
    op.create_index(op.f('ix_alerts_phase_concernee'), 'alerts', ['phase_concernee'], unique=False)
    op.create_index(op.f('ix_alerts_priorite'), 'alerts', ['priorite'], unique=False)
    op.create_index(op.f('ix_alerts_statut'), 'alerts', ['statut'], unique=False)
    op.create_index(op.f('ix_alerts_type_alerte'), 'alerts', ['type_alerte'], unique=False)
    op.create_index(op.f('ix_alerts_type_systeme'), 'alerts', ['type_systeme'], unique=False)
    op.create_table('device_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('appareil_id', sa.String(length=36), nullable=False),
    sa.Column('peut_voir', sa.Boolean(), nullable=False),
    sa.Column('peut_controler', sa.Boolean(), nullable=False),
    sa.Column('peut_configurer', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appareil_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'appareil_id', name='unique_user_device_access')
    )
    op.create_index(op.f('ix_device_access_actif'), 'device_access', ['actif'], unique=False)
    op.create_index(op.f('ix_device_access_appareil_id'), 'device_access', ['appareil_id'], unique=False)
    op.create_index(op.f('ix_device_access_utilisateur_id'), 'device_access', ['utilisateur_id'], unique=False)
    op.create_table('device_action_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_subtype', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appareil_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('type_systeme', sa.Enum('monophase', 'triphase', name='system_type'), nullable=False),
    sa.Column('tension', sa.Float(), nullable=True),
    sa.Column('courant', sa.Float(), nullable=True),
    sa.Column('puissance', sa.Float(), nullable=True),
    sa.Column('energie', sa.Float(), nullable=True),
    sa.Column('tension_l1', sa.Float(), nullable=True),
    sa.Column('tension_l2', sa.Float(), nullable=True),
    sa.Column('tension_l3', sa.Float(), nullable=True),
    sa.Column('courant_l1', sa.Float(), nullable=True),
    sa.Column('courant_l2', sa.Float(), nullable=True),
    sa.Column('courant_l3', sa.Float(), nullable=True),
    sa.Column('courant_neutre', sa.Float(), nullable=True),
    sa.Column('puissance_l1', sa.Float(), nullable=True),
    sa.Column('puissance_l2', sa.Float(), nullable=True),
    sa.Column('puissance_l3', sa.Float(), nullable=True),
    sa.Column('puissance_totale', sa.Float(), nullable=True),
    sa.Column('puissance_reactive_l1', sa.Float(), nullable=True),
    sa.Column('puissance_reactive_l2', sa.Float(), nullable=True),
    sa.Column('puissance_reactive_l3', sa.Float(), nullable=True),
    sa.Column('puissance_reactive_totale', sa.Float(), nullable=True),
    sa.Column('puissance_apparente_l1', sa.Float(), nullable=True),
    sa.Column('puissance_apparente_l2', sa.Float(), nullable=True),
    sa.Column('puissance_apparente_l3', sa.Float(), nullable=True),
    sa.Column('puissance_apparente_totale', sa.Float(), nullable=True),
    sa.Column('facteur_puissance_l1', sa.Float(), nullable=True),
    sa.Column('facteur_puissance_l2', sa.Float(), nullable=True),
    sa.Column('facteur_puissance_l3', sa.Float(), nullable=True),
    sa.Column('facteur_puissance_total', sa.Float(), nullable=True),
    sa.Column('frequence', sa.Float(), nullable=True),
    sa.Column('energie_l1', sa.Float(), nullable=True),
    sa.Column('energie_l2', sa.Float(), nullable=True),
    sa.Column('energie_l3', sa.Float(), nullable=True),
    sa.Column('energie_totale', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidite', sa.Float(), nullable=True),
    sa.Column('etat_switch', sa.Boolean(), nullable=True),
    sa.Column('donnees_brutes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_data_time', 'device_data', ['client_id', 'horodatage'], unique=False)
    op.create_index('idx_device_data_time', 'device_data', ['appareil_id', 'horodatage'], unique=False)
    op.create_index('idx_system_type_time', 'device_data', ['type_systeme', 'horodatage'], unique=False)
    op.create_index(op.f('ix_device_data_appareil_id'), 'device_data', ['appareil_id'], unique=False)
    op.create_index(op.f('ix_device_data_client_id'), 'device_data', ['client_id'], unique=False)
    op.create_index(op.f('ix_device_data_horodatage'), 'device_data', ['horodatage'], unique=False)
    op.create_index(op.f('ix_device_data_type_systeme'), 'device_data', ['type_systeme'], unique=False)
    op.create_table('protection_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('appareil_id', sa.String(length=36), nullable=False),
    sa.Column('type_protection', sa.Enum('courant_depasse', 'puissance_depassee', 'temperature_haute', 'tension_anormale', 'desequilibre_tension', 'desequilibre_courant', 'perte_phase', 'facteur_puissance_faible', 'autre', name='protection_event_types'), nullable=False),
    sa.Column('type_systeme', sa.Enum('monophase', 'triphase', name='system_type_protection'), nullable=False),
    sa.Column('phase_concernee', sa.Enum('L1', 'L2', 'L3', 'neutre', 'toutes', name='phase_protection'), nullable=True),
    sa.Column('action_effectuee', sa.Enum('arret_appareil', 'reduction_puissance', 'alerte_envoyee', 'redemarrage_auto', 'mode_securite', 'aucune_action', name='protection_actions'), nullable=False),
    sa.Column('etat_avant', sa.String(length=20), nullable=True),
    sa.Column('etat_apres', sa.String(length=20), nullable=True),
    sa.Column('valeur_declenchement', sa.Float(), nullable=True),
    sa.Column('valeur_seuil', sa.Float(), nullable=True),
    sa.Column('unite_mesure', sa.String(length=10), nullable=True),
    sa.Column('valeurs_phases', sa.JSON(), nullable=True),
    sa.Column('timestamp_declenchement', sa.DateTime(), nullable=False),
    sa.Column('timestamp_resolution', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'resolu_auto', 'resolu_manuel', 'ignore', 'erreur', name='protection_event_status'), nullable=False),
    sa.Column('resolu_par', sa.String(length=36), nullable=True),
    sa.Column('methode_resolution', sa.String(length=100), nullable=True),
    sa.Column('duree_minutes', sa.Float(), nullable=True),
    sa.Column('config_protection', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details_techniques', sa.JSON(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appareil_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protection_events_appareil_id'), 'protection_events', ['appareil_id'], unique=False)
    op.create_index(op.f('ix_protection_events_client_id'), 'protection_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_protection_events_statut'), 'protection_events', ['statut'], unique=False)
    op.create_index(op.f('ix_protection_events_timestamp_declenchement'), 'protection_events', ['timestamp_declenchement'], unique=False)
    op.create_index(op.f('ix_protection_events_type_protection'), 'protection_events', ['type_protection'], unique=False)
    op.create_index(op.f('ix_protection_events_type_systeme'), 'protection_events', ['type_systeme'], unique=False)
    op.create_table('scheduled_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('appareil_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('turn_on', 'turn_off', 'toggle', 'custom_command', 'restart', 'standby', 'protection_mode', name='scheduled_action_types'), nullable=False),
    sa.Column('custom_command', sa.JSON(), nullable=True),
    sa.Column('heure_execution', sa.Time(), nullable=False),
    sa.Column('jours_semaine', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('mode_execution', sa.Enum('once', 'daily', 'weekly', 'custom', name='execution_modes'), nullable=False),
    sa.Column('prochaine_execution', sa.DateTime(), nullable=True),
    sa.Column('derniere_execution', sa.DateTime(), nullable=True),
    sa.Column('derniere_execution_success', sa.Boolean(), nullable=True),
    sa.Column('derniere_execution_error', sa.Text(), nullable=True),
    sa.Column('executions_totales', sa.Integer(), nullable=False),
    sa.Column('executions_reussies', sa.Integer(), nullable=False),
    sa.Column('executions_echouees', sa.Integer(), nullable=False),
    sa.Column('nom_action', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.String(length=36), nullable=True),
    sa.Column('retry_enabled', sa.Boolean(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appareil_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_actions_actif'), 'scheduled_actions', ['actif'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_action_type'), 'scheduled_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_appareil_id'), 'scheduled_actions', ['appareil_id'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_client_id'), 'scheduled_actions', ['client_id'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_heure_execution'), 'scheduled_actions', ['heure_execution'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_prochaine_execution'), 'scheduled_actions', ['prochaine_execution'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_actions_prochaine_execution'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_heure_execution'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_client_id'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_appareil_id'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_action_type'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_actif'), table_name='scheduled_actions')
    op.drop_table('scheduled_actions')
    op.drop_index(op.f('ix_protection_events_type_systeme'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_type_protection'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_timestamp_declenchement'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_statut'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_client_id'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_appareil_id'), table_name='protection_events')
    op.drop_table('protection_events')
    op.drop_index(op.f('ix_device_data_type_systeme'), table_name='device_data')
    op.drop_index(op.f('ix_device_data_horodatage'), table_name='device_data')
    op.drop_index(op.f('ix_device_data_client_id'), table_name='device_data')
    op.drop_index(op.f('ix_device_data_appareil_id'), table_name='device_data')
    op.drop_index('idx_system_type_time', table_name='device_data')
    op.drop_index('idx_device_data_time', table_name='device_data')
    op.drop_index('idx_client_data_time', table_name='device_data')
    op.drop_table('device_data')
    op.drop_table('device_action_logs')
    op.drop_index(op.f('ix_device_access_utilisateur_id'), table_name='device_access')
    op.drop_index(op.f('ix_device_access_appareil_id'), table_name='device_access')
    op.drop_index(op.f('ix_device_access_actif'), table_name='device_access')
    op.drop_table('device_access')
    op.drop_index(op.f('ix_alerts_type_systeme'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_type_alerte'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_statut'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priorite'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_phase_concernee'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_gravite'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_date_creation'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_client_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_appareil_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_prenom'), table_name='users')
    op.drop_index(op.f('ix_users_nom'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_index(op.f('ix_users_actif'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_type_systeme'), table_name='devices')
    op.drop_index(op.f('ix_devices_tuya_device_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_statut_assignation'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_protection_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_protection_automatique_active'), table_name='devices')
    op.drop_index(op.f('ix_devices_programmation_active'), table_name='devices')
    op.drop_index(op.f('ix_devices_en_ligne'), table_name='devices')
    op.drop_index(op.f('ix_devices_client_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_actif'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_sites_client_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_actif'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_clients_nom_entreprise'), table_name='clients')
    op.drop_index(op.f('ix_clients_email_contact'), table_name='clients')
    op.drop_index(op.f('ix_clients_actif'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
