"""Add etat_actuel_tuya to Device model

Revision ID: c39e40aac3e0
Revises: d4afe16e8f96
Create Date: 2025-07-06 20:56:01.070318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39e40aac3e0'
down_revision = 'd4afe16e8f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat_actuel_tuya', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('derniere_maj_etat_tuya', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('derniere_maj_etat_tuya')
        batch_op.drop_column('etat_actuel_tuya')

    # ### end Alembic commands ###
