"""Creation initiale toutes tables

Revision ID: d4afe16e8f96
Revises: daecd76b9a62
Create Date: 2025-07-06 14:24:38.384472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4afe16e8f96'
down_revision = 'daecd76b9a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection_tension_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('protection_desequilibre_config', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_site_id'), ['site_id'], unique=False)
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_site_id'))
        batch_op.drop_column('site_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('protection_desequilibre_config')
        batch_op.drop_column('protection_tension_config')

    # ### end Alembic commands ###
