"""Initial migration with all tables

Revision ID: d51382a0ae9c
Revises: 
Create Date: 2025-10-09 17:21:44.272064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd51382a0ae9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.drop_column('tension_l2_l3')
        batch_op.drop_column('tension_l1_l2')
        batch_op.drop_column('tension_l3_l1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tension_l3_l1', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tension_l1_l2', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tension_l2_l3', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
