"""Ajout assignation appareils et infos Tuya

Revision ID: ede8bb64ccc4
Revises: 
Create Date: 2025-06-13 22:26:09.854876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ede8bb64ccc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut_assignation', sa.Enum('non_assigne', 'assigne', name='device_assignment_status'), nullable=False))
        batch_op.add_column(sa.Column('tuya_nom_original', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tuya_modele', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tuya_version_firmware', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_assignation', sa.DateTime(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('site_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_devices_statut_assignation'), ['statut_assignation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_statut_assignation'))
        batch_op.alter_column('site_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('date_assignation')
        batch_op.drop_column('tuya_version_firmware')
        batch_op.drop_column('tuya_modele')
        batch_op.drop_column('tuya_nom_original')
        batch_op.drop_column('statut_assignation')

    # ### end Alembic commands ###
